apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev

patchesStrategicMerge:
- env-vars.yaml

images:
- name: apples-service
  newName: /
  newTag: 1.0.30
