apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: prod

patchesStrategicMerge:
- env-vars.yaml
images:
- name: apples-service
  newName: apples-service
  newTag: 1.0.0
