name: deploy

inputs:
  env:
    required: true
  service-name:
    required: true
  registry:
    required: true
  image-name:
    required: true
  tag-name:
    required: true

runs:
  using: composite

  steps:
    - name: Set git config
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Pull changes
      shell: bash
      run: |
        git pull

    - name: Update image
      shell: bash
      run: |
        cd overlays/${{ inputs.env }}
        kustomize edit set image ${{ inputs.service-name }}=${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.tag-name }}

    - name: Push changes
      shell: bash
      run: |
        git commit -am "[${{ inputs.env }}] update ${{ inputs.service-name }} image to ${{ inputs.tag-name }}"
        git push
